server:
    port: 9091
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:9090/eureka
spring:
  application:
    name: ApiGateway
  cloud:
    gateway:
      routes:
        - id: EmployeeService
          uri: lb://EmployeeService
          predicates:
            - Path=/employees/**
          filters:
            - name: CircuitBreaker
              args:
                name: EmployeeService
                fallbackuri: forward:/employeeservicefallback
        - id: DepartmentService
          uri: lb://DepartmentService
          predicates:
            - Path=/departments/**
          filters:
            - name: CircuitBreaker
              args:
                name: DepartmentService
                fallbackuri: forward:/departmentservicefallback

hystrix:
  command:
    fallbackcmd:
      execution:
        isolation:
          thread:
            timeoutInMilliseconds: 4000

management:
  endpoints:
    web:
      exposure:
        include: hystrix.stream