server:
    port: 9093
eureka:
    client:
        serviceUrl: 
            defaultZone: http://localhost:9090/eureka
spring:
    application:
        name: EmployeeService
    datasource:
        driver-class-name: com.mysql.cj.jdbc.Driver
        url: jdbc:mysql://localhost:3306/employeeservice?serverTimezone=UTC
        username: root
        password: root
        nitialization-mode: always
    jpa:
        hibernate:
            ddl-auto: update